// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"cicd2jenkins/internal/config"
	"cicd2jenkins/internal/logic"
	"cicd2jenkins/internal/repo"
	"cicd2jenkins/internal/repo/gormrepo"
	"cicd2jenkins/internal/service"
	"cicd2jenkins/internal/transport/httpapi"
	"cicd2jenkins/internal/transport/httpapi/middleware"
	"github.com/google/wire"
	"net/http"
)

// Injectors from wire.go:

func initializeServer(cfg config.Config) (*http.Server, func(), error) {
	v, err := provideSeedUsers(cfg)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := provideDatabase(cfg, v)
	if err != nil {
		return nil, nil, err
	}
	userRepository := provideUserRepository(db)
	authLogic := provideAuthLogic(cfg, userRepository)
	authService := service.NewAuthService(authLogic)
	articleRepository := provideArticleRepository(db)
	articleLogic := logic.NewArticleLogic(articleRepository)
	articleService := service.NewArticleService(articleLogic)
	authMiddleware := middleware.NewAuthMiddleware(authLogic)
	handler := httpapi.NewRouter(authService, articleService, authMiddleware)
	server := provideHTTPServer(cfg, handler)
	return server, func() {
		cleanup()
	}, nil
}

// wire.go:

var serverSet = wire.NewSet(
	provideSeedUsers,
	provideDatabase,
	provideUserRepository,
	provideArticleRepository,
	provideAuthLogic, logic.NewArticleLogic, service.NewAuthService, service.NewArticleService, middleware.NewAuthMiddleware, httpapi.NewRouter, provideHTTPServer, wire.Bind(new(repo.ArticleRepository), new(*gormrepo.ArticleRepository)), wire.Bind(new(repo.UserRepository), new(*gormrepo.UserRepository)),
)
