// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"cicd2jenkins/internal/config"
	"cicd2jenkins/internal/repository"
	"cicd2jenkins/internal/repository/elasticsearch"
	"cicd2jenkins/internal/repository/memory"
	"cicd2jenkins/internal/service"
	"cicd2jenkins/internal/transport/httpapi"
	"github.com/google/wire"
	"net/http"
)

// Injectors from wire.go:

func initializeServer(cfg config.Config) (*http.Server, error) {
	v, err := provideSeedUsers(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := provideUserRepository(v)
	authService := provideAuthService(cfg, userRepository)
	client, err := provideElasticsearchClient(cfg)
	if err != nil {
		return nil, err
	}
	articleRepository, err := provideArticleRepository(cfg, client)
	if err != nil {
		return nil, err
	}
	articleService := service.NewArticleService(articleRepository)
	handler := httpapi.NewRouter(authService, articleService)
	server := provideHTTPServer(cfg, handler)
	return server, nil
}

// wire.go:

var serverSet = wire.NewSet(
	provideElasticsearchClient,
	provideArticleRepository,
	provideSeedUsers,
	provideUserRepository,
	provideAuthService, service.NewArticleService, httpapi.NewRouter, provideHTTPServer, wire.Bind(new(repository.ArticleRepository), new(*elasticsearch.ArticleRepository)), wire.Bind(new(repository.UserRepository), new(*memory.UserRepository)),
)
